<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'model.content.adress' => '',
  'model.content.city' => '',
  'model.content.content' => '',
  'model.content.create_time' => '',
  'model.content.created_by' => '',
  'model.content.email' => '',
  'model.content.excerpt' => '',
  'model.content.fax' => '',
  'model.content.file' => '',
  'model.content.id' => '',
  'model.content.img' => '',
  'model.content.index' => '',
  'model.content.parent_id' => '',
  'model.content.pib' => '',
  'model.content.status' => '',
  'model.content.tel' => '',
  'model.content.text' => '',
  'model.content.title' => '',
  'model.content.update_time' => '',
  'model.content.updated_by' => '',
  'model.menu.create_time' => '',
  'model.menu.created_by' => '',
  'model.menu.description' => '',
  'model.menu.id' => '',
  'model.menu.status' => '',
  'model.menu.title' => '',
  'model.menu.update_time' => '',
  'model.menu.updated_by' => '',
  'model.menuitem.create_time' => '',
  'model.menuitem.created_by' => '',
  'model.menuitem.id' => '',
  'model.menuitem.list_order' => '',
  'model.menuitem.menu_id' => '',
  'model.menuitem.model_id' => '',
  'model.menuitem.model_name' => '',
  'model.menuitem.status' => '',
  'model.menuitem.update_time' => '',
  'model.menuitem.updated_by' => '',
  'model.seo.id' => '',
  'model.seo.model_id' => '',
  'model.seo.model_name' => '',
  'model.seo.status' => '',
  'model.seo.url' => '',
  'model.seo.view' => '',
  'model.user.email' => '',
  'model.user.first_name' => '',
  'model.user.id' => '',
  'model.user.last_name' => '',
  'model.user.password' => '',
  'model.user.username' => '',
);
